version: '3.8'

services:

    db:
        restart: always
        image: postgres
        env_file:
            - ./app/.env
        volumes:
            - postgres-data-db:/var/lib/postgresql/data

    testapp:
        build:
            context: ./app
        volumes:
        - ./app:/app
        depends_on:
            - db

volumes:
    postgres-data-db: